version: '2.0'

services:
  software-project-management-frontend:
    build:
      context: software-project-management-frontend
      dockerfile: Dockerfile
    command: ng serve --host 0.0.0.0
    volumes:
      - ./software-project-management-frontend:/usr/src/app
      - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'
    depends_on:
      - orchrestator
  orchrestator:
    build:
      context: orchestrator-and-auth
      dockerfile: Dockerfile
    volumes:
      - ./orchestrator-and-auth:/app
    ports:
      - '8000:8000'
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - project-managers-interface
      - user-stories-assignment
      - task-assignment
  project-managers-interface:
    build:
      context: project-managers-interface
      dockerfile: Dockerfile
    volumes:
      - ./project-managers-interface:/usr/src/app
      - '/usr/src/app/node_modules'
    command:  npm run watch 
    ports:
      - '3000:3000'
  user-stories-assignment:
    build: 
      context: user-stories-assignment-service
      dockerfile: Dockerfile
    command: npm run watch 
    volumes:
      - ./user-stories-assignment-service:/usr/src/app
      - '/usr/src/app/node_modules'
    ports:
      - "3001:3001"
    depends_on:
      - task-assignment
  task-assignment:
    build: 
      context: task-assignment-service
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./task-assignment-service:/app
    ports:
      - "8001:8001"